# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/go-caffe"

[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go-sourcepath"

[[constraint]]
  name = "github.com/Unknwon/com"
  version = "1.0.0"

[[constraint]]
  name = "github.com/anthonynsimon/bild"
  version = "0.10.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[override]]
  branch = "master"
  name = "github.com/ianlancetaylor/cgosymbolizer"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/config"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/dlframework"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/downloadmanager"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/logger"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/nvidia-smi"

[[constraint]]
  branch = "master"
  name = "github.com/rai-project/tracer"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[override]]
  branch = "master"
  name = "github.com/apache/thrift"

[[override]]
  name = "github.com/k0kubun/pp"
  version = "3.0.1"

[prune]
  go-tests = true
  unused-packages = true
